### ISSUE TITLE
Failed build on IRIX

### ISSUE THREAD

**Issue by gwfisher** [p11-glue/p11-kit#101]
I'm trying to build P11-kit on IRIX so I can build gnutls. However, it's giving me this error when I compile it. I've tried it with both MIPSPro (SGI's proprietary compiler) and GCC with no such luck. As I understand this also happens on AIX.

Is there anyway I can get this to work?

Any help is appreciated!

bash-4.3$ gmake
gmake  all-recursive
gmake[1]: Entering directory `/usr/people/wfisher/p11-kit-0.23.3'
Making all in .
gmake[2]: Entering directory `/usr/people/wfisher/p11-kit-0.23.3'
  CC       common/compat.lo
common/compat.c: In function 'getprogname':
common/compat.c:118:3: error: #error No way to retrieve short program name
common/compat.c: In function 'strerror_r':
common/compat.c:854:3: error: #error no strerror_r implementation
common/compat.c: In function 'fdwalk':
common/compat.c:894:8: warning: implicit declaration of function 'dirfd' [-Wimplicit-function-declaration]
common/compat.c:894:8: warning: nested extern declaration of 'dirfd' [-Wnested-externs]
common/compat.c: In function 'strerror_r':
common/compat.c:856:1: warning: control reaches end of non-void function [-Wreturn-type]
gmake[2]: *** [common/compat.lo] Error 1
gmake[2]: Leaving directory `/usr/people/wfisher/p11-kit-0.23.3'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/usr/people/wfisher/p11-kit-0.23.3'
gmake: *** [all] Error 2

**Comment by nmav** [comment]
If you don't use p11-kit functionality in gnutls, then simply disable it. The system seems to miss important posix functionality such as strerror_r(). Closing it, but please feel free to open a merge request to address such portability issues.
