### ISSUE TITLE
Raspbian p11-kit: no configured writable location to store anchors

### ISSUE THREAD

**Issue by anthonygreen** [p11-glue/p11-kit#115]
on Raspbian 

    sudo trust anchor MyCRT.crt 

errors

    p11-kit: no configured writable location to store anchors

Improving the error to suggest pointers to a solution may be a worthwhile interim fix

**Comment by ueno** [comment]
I am afraid I have no idea how it could be improved at the upstream level, as the use-case is currently unsupported on Debian. See [the mailing list discussion](https://lists.freedesktop.org/archives/p11-glue/2017-July/000672.html) and the linked Debian bugs from there for the background. In short, even if you made the command work somehow and stored the certificate, no practical application in Debian would be able to read it.

**Comment by nmav** [comment]
I think that it makes sense to consider that as a downstream issue (rasbian/debian), rather than p11-kit issue.

**Comment by mohammedzeglam-pg** [comment]
how to fix this issue in arch linux

**Comment by grstein** [comment]
> how to fix this issue in arch linux

use *sudo*
