### ISSUE TITLE
manual to simpler to docbook form

### ISSUE THREAD

**Issue by nmav** [p11-glue/p11-kit#118]
While docbook seems to have some leverage with gnome, it is phased out as a documentation format in favor of simpler forms such as markdown. I find that such a move would simplify the update/addition of new documentation pages.

**Comment by ueno** [comment]
I think that depends on whether the new format is supported by gtk-doc (I usually browse the documentation with devhelp and don't want to lose the convenience). Apparently gtk-doc supports markdown in the inline comments, but I couldn't find any use in the documentation skeletons. If there is any example doing that, we could follow.

**Comment by nmav** [comment]
Closing as wontfix
