### ISSUE TITLE
en@boldquot.po and en@quot.po are missing from git repo

### ISSUE THREAD

**Issue by kanavin** [p11-glue/p11-kit#127]
All other .po files seem to be there, but not these two. Probably they should be committed? We (the yocto project) are running into build issues because of it.

**Comment by ueno** [comment]
Could you provide a link to the actual issue? Those files are generated by gettext's build infrastructure, and thus shouldn't be version controlled in git.  See:
https://www.gnu.org/software/gettext/manual/html_node/po_002fLINGUAS.html#po_002fLINGUAS

**Comment by kanavin** [comment]
The particular issue I've been seeing with the trying to build the git checkout was:

| File en@quot.po does not exist. If you are a translator, you can create it through 'msginit'.

and  I solved it by patching LINGUAS. Note that the tarballs do supply these two files, and so things work. 

I think we're not running gettextize though (for various complicated reasons), I'll ask a colleague to add his 2 cents. Might be our problem; bear with us please :)

**Comment by rossburton** [comment]
Yes, we need to run more of the tooling.  autogen does gettextize and autopoint (via autoreconf) so we need to do those too.
