### ISSUE TITLE
uselocale vs. strerror_l

### ISSUE THREAD

**Issue by 0-wiz-0** [p11-glue/p11-kit#143]
The code assumes that when `strerror_l` exists, `uselocale` must also exist. That is wrong on at least NetBSD.
Please check for `uselocale` separately.

See
https://github.com/p11-glue/p11-kit/blob/master/common/debug.c#L165
and
https://github.com/p11-glue/p11-kit/blob/master/common/message.c#L121

**Comment by ueno** [comment]
On such environment, how do you get the current locale as `locale_t` object without `uselocale`?

**Comment by 0-wiz-0** [comment]
I had to ask around, since I don't know much about this. The answer was: Depends on what you want: you can use `newlocale(3)`, `LC_GLOBAL_LOCALE` or `LC_C_LOCALE`. NetBSD by purpose does not support thread-specific locales, and thus also does not support `uselocale()`. Hope this helps.

**Comment by ueno** [comment]
Thank you for checking that.  In that case, I guess the best option would be to fallback to `strerror_r()`, as #144.
