### ISSUE TITLE
Add configure option --with-issetugid-openbsd[=yes|no]

### ISSUE THREAD

**Issue by pullmoll** [p11-glue/p11-kit#169]
After the commit [common: Don't rely on issetugid() when it is broken](https://github.com/p11-glue/p11-kit/commit/71b62aa1cdbdec3724c8e451f621309994dc59a0) when we try to compile p11-kit for `musl libc` cross target architectures, running the brokenness test fails for obvious reasons. For `glibc` cross targets that test is not run.

Instead of [patching away the test in `configure.ac`](https://github.com/voidlinux/void-packages/pull/14811), which we would need to do, it'd be good to have a configure option like `--with-issetugid-openbsd[=yes|no]` to tell configure to not run that test but just add or not add `#define HAVE_ISSETUGID_OPENBSD 1` accordingly.

**Comment by ueno** [comment]
I don't understand your problem.  First, `issetugid()` is only used for emulating `getauxval()`, while musl-libc actually provides a working `getauxval()`.  Second, if the configure check detects `issetugid()` is broken, that means it cannot be used for emulating `getauxval()` (see the [issetugid sadness article](https://gist.github.com/nicowilliams/4daf74a3a0c86848d3cbd9d0cdb5e26e) linked from the commit).

Could you please elaborate the problem you are trying to solve (e.g. by providing the error logs)? I can successfully run `./configure` and `make check` on Alpine Linux 3.5.2 from http://www.nongnu.org/pretest/.

**Comment by ueno** [comment]
Ah, sorry I missed the fact that this is about cross-compiling; now I see your point.
I think the proper fix would be to wrap the check with AC_CACHE_CHECK so that the user can skip the check by setting an envvar.  I have opened #170 for this.

**Comment by pullmoll** [comment]
Thanks a lot @ueno! I think we can work with this. I'm not deep into the issetguid() issue at all and will certainly wait for the more experienced team members to tell what we should do then.
