### ISSUE TITLE
Hide getauxval() symbol

### ISSUE THREAD

**Issue by prlw1** [p11-glue/p11-kit#192]
Just letting you know of a bug filed and fixed at: http://gnats.netbsd.org/53387

Essentially
```
assertion "type == AT_SECURE" failed: file "common/compat.c", line 801,
function "getauxval"
[1]   Abort trap (core dumped) scanimage
```

Fixed with the first section of: http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/security/p11-kit/patches/patch-common_compat.c

**Comment by ueno** [comment]
I'm closing this as we haven't hear any further information for a long time. Please feel free to reopen if the problem still persists.
