### ISSUE TITLE
[MacOS/X, P11-kit 0.23.14] When running "make check", test_init_pin fails

### ISSUE THREAD

**Issue by young-git2046** [p11-glue/p11-kit#197]
Summary: "test_init_pin" fails because teardown_mock_module()
  is missing a call to cleanup.

In p11-kit/test-proxy.c:
The static function teardown_mock_module() seems to be missing a call
to p11_proxy_module_cleanup(). This leads to an exhaustion of the cells
available in fixed_closures[] (see in p11-kit/virtual.c), meaning a test
may fail because the test previously run didn't free all the cells in
fixed_closures[].

Such an exhaustion leads to the failure of the test "test_init_pin".

The attached patch addresses this problem.

Local config:
* uname -a
[...] Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64

* call to configure:
./configure --without-libffi --without-libtasn1 --without-gtk-doc --without-xlstproc --without-freebl3 --enable-doc=no --with-system-config=/usr/local/etc -enable-debug

 No problem encountered while running configure, nor while compiling
 through make.

[test-proxy.diff.txt](https://github.com/p11-glue/p11-kit/files/2499304/test-proxy.diff.txt)

**Comment by ueno** [comment]
Thank you for the detail investigation! It seems like a real issue, so I have filed #199 (with --without-libffi enabled on macOS CI).
