### ISSUE TITLE
Java cacerts file incomplete when two root certificates with same subject is added

### ISSUE THREAD

**Issue by FOTempel** [p11-glue/p11-kit#207]
When two certificates are put into /etc/pki/ca-trust/source/anchors which are different but have the same subject, only one of the two gets added to /etc/pki/ca-trust/extracted/java/cacerts by update-ca-trust (p11-kit).

Use case:
Root - 8 years validity
Intermediate - 4 years validity
Issued certificate - 2 years validity

To make sure the intermediate CA keeps issuing certificates which are valid for two years, its signing certificate has to be replaced at half of its validity period. In this use case a new intermediate certificate has been put in the issuing (intermediate) CA with the same subject as the old one and hence forward all newly issued certificates are signed with this new intermediate certificate. Obviously, all certificates signed with the previous intermediate certificate continue to be trusted.

p11-kit cannot deal with two (or more, but our CA isn't that old yet) valid root certificates with the same subject (or rather CN) when it comes to the central Java keystore.

**Comment by ueno** [comment]
I tried it by myself, but the generated JKS file actually contains both certificates according to `keytool -list`.  There is an issue though: one of those duplicated certs has a strange alias (e.g., "-1"), which I am fixing in #208.  Is it what you mean?

Otherwise, could you provide the steps to reproduce?

**Comment by FOTempel** [comment]
Hi. Sorry for the late reply. But you're right, that is the same issue! I didn't think of looking for some random generated alias, to be honest.

**Comment by ueno** [comment]
Thank you for the confirmation.  Closing then.
