### ISSUE TITLE
PKCS#11 3.0

### ISSUE THREAD

**Issue by ueno** [p11-glue/p11-kit#214]
Although it is still in the "Draft" state, it would be nice to prepare for the upcoming changes in PKCS#11 3.0, in particular the new entry point functions (`C_GetInterface`, etc).

https://www.oasis-open.org/committees/documents.php?wg_abbrev=pkcs11&show_descriptions=yes

**Comment by bgermann** [comment]
OpenSC [updated their version](https://github.com/OpenSC/OpenSC/commit/9be6dc66067cfa5c1ed4e74d32c70af52d8bea29) of the PKCS#11 headers with release 0.22.0 to support PKCS#11 3.0.

**Comment by ueno** [comment]
Now it should be done through the decomposed PRs, e.g., #461, #463, ...
