### ISSUE TITLE
Compiling issue on fresh linux from scratch built

### ISSUE THREAD

**Issue by Rndwiga** [p11-glue/p11-kit#216]
=======================================
   p11-kit 0.23.13: ./test-suite.log
=======================================

# TOTAL: 752
# PASS:  751
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-token
================

1..21
ok 1 /token/load
PASS: test-token 1 /token/load
ok 2 /token/flags
PASS: test-token 2 /token/flags
ok 3 /token/path
PASS: test-token 3 /token/path
ok 4 /token/label
PASS: test-token 4 /token/label
ok 5 /token/slot
PASS: test-token 5 /token/slot
not ok 6 /token/not-writable
FAIL: test-token 6 /token/not-writable
# assertion failed (!p11_token_is_writable (token))
# test-token: assertion failed (!p11_token_is_writable (token))
# in test_not_writable() at test-token.c:256
# test-token: in test_not_writable() at test-token.c:256
ok 7 /token/writable-no-exist
PASS: test-token 7 /token/writable-no-exist
ok 8 /token/writable-exists
PASS: test-token 8 /token/writable-exists
ok 9 /token/load-found
PASS: test-token 9 /token/load-found
ok 10 /token/load-already
PASS: test-token 10 /token/load-already
ok 11 /token/load-unreadable
PASS: test-token 11 /token/load-unreadable
ok 12 /token/load-gone
PASS: test-token 12 /token/load-gone
ok 13 /token/load-contrived
PASS: test-token 13 /token/load-contrived
ok 14 /token/reload-changed
PASS: test-token 14 /token/reload-changed
ok 15 /token/reload-gone
PASS: test-token 15 /token/reload-gone
ok 16 /token/reload-no-origin
PASS: test-token 16 /token/reload-no-origin
ok 17 /token/write-new
PASS: test-token 17 /token/write-new
ok 18 /token/write-no-label
PASS: test-token 18 /token/write-no-label
ok 19 /token/modify-multiple
PASS: test-token 19 /token/modify-multiple
ok 20 /token/remove-one
PASS: test-token 20 /token/remove-one
ok 21 /token/remove-multiple
PASS: test-token 21 /token/remove-multiple

**Comment by ueno** [comment]
2 questions:
- how did you build the tarball and run the tests?
- does this happen with the latest release (0.23.15)?

**Comment by ueno** [comment]
I'm closing this as we haven't hear any further information for a long time. Please feel free to reopen if the problem still persists.

**Comment by noloader** [comment]
@ueno,

This issue is still present in both P11-Kit 0.23.19 and 0.23.20.
