### ISSUE TITLE
Proxy: Update slot list during each call to C_GetSlotList()

### ISSUE THREAD

**Issue by dpward** [p11-glue/p11-kit#221]
When an application calls `C_Initialize()` in the proxy module, the proxy calls `C_GetSlotList()` in all of the p11-kit modules and assigns each slot a "wrapped" slot ID. The proxy never checks for new slots in the p11-kit modules after this; it always returns the same slots whenever the application calls `C_GetSlotList()`. (However the proxy will filter the returned slot list if the `tokenPresent` parameter is `TRUE`; to do this it will call `C_GetSlotInfo()` for each slot to determine if a token is present.)

Although this is [valid behavior in PKCS#11](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959741), it imposes a usability limitation that does not exist if the individual PKCS#11 modules (such as OpenSC) are installed directly in the NSS database instead.

For example, if Firefox and/or Thunderbird are open, and the user now plugs in a Yubikey or attaches the laptop to a docking station connected to a USB keyboard with a smart card reader, these will not be usable by Firefox or Thunderbird via the proxy until those applications are completely closed and re-opened.

**Comment by ueno** [comment]
Thank you for looking into it. That is a good suggestion. I've opened #224 to fix this.
