### ISSUE TITLE
Proxy: Handle non-blocking calls to C_WaitForSlotEvent()

### ISSUE THREAD

**Issue by dpward** [p11-glue/p11-kit#222]
Currently, all calls to `C_WaitForSlotEvent()` in the proxy module [return `CKR_FUNCTION_NOT_SUPPORTED`](https://github.com/p11-glue/p11-kit/blob/793cc3b78f17bb5a3c151eba1144b73a5d51be3e/p11-kit/proxy.c#L576).

While _blocking_ calls might not be practical to handle, is anything known that would prevent _non-blocking_ calls from being handled correctly (where `CKF_DONT_BLOCK` is set in `flags`)?

Some applications appear not to work if the PKCS#11 module cannot handle non-blocking `C_WaitForSlotEvent()`. In particular I have noticed this with VMware Horizon Client for Linux.

**Comment by ueno** [comment]
@stefwalter do you happen to remember the reason why we don't delegate `C_WaitForSlotEvent()` to the underlying modules?

**Comment by stefwalter** [comment]
@ueno I think because it's not possible to simply do that when you have multiple modules. I believe one would need to start new threads or figure out how to interleave waits ... It seemed to complicated at the time.

**Comment by dpward** [comment]
@stefwalter What about `C_WaitForSlotEvent(CKF_DONT_BLOCK)` though? That's a non-blocking call to each module.

**Comment by stefwalter** [comment]
Indeed. Seems like that could work.

**Comment by ueno** [comment]
Thank you both for the suggestion and the explanation. I've implemented it as #225.
@dpward do you know which application actually uses this feature? I captured the PKCS#11 interaction in Firefox but it doesn't seem to use it.
