### ISSUE TITLE
valid-date test failure when daylight

### ISSUE THREAD

**Issue by alonbl** [p11-glue/p11-kit#235]
Hi,
Please refer to [1], the date validation is failing because `mktime()` modify the `struct tm` based on daylight settings in some timezone, in our case `Europe/Dublin`, as `mktime()` is using local time.
I do not fully understand the test done at this[2] location, why is it not sufficient to check `(time_t)-1` result of `mktime()`, I would have just remove it... as construction of dates in `PKCS#11` should be UTC anyway.
An option is to use `timegm()` or `_mkgmtime()` in Windows, however, it is not that relevant as I do not see any `mktime()` usage within the core code, so it is not that we need to test the behavior of `mktime()` compared of what expected.
I suggest to remove this.
Thanks!

[1] https://bugs.gentoo.org/show_bug.cgi?id=688460
[2] https://github.com/p11-glue/p11-kit/blob/master/trust/builder.c#L263

**Comment by alonbl** [comment]
I now realize that the test was in core, so I modified it to ignore timezone.

**Comment by ueno** [comment]
> as construction of dates in PKCS#11 should be UTC anyway.

Do you have any reference about this?

**Comment by alonbl** [comment]
> > as construction of dates in PKCS#11 should be UTC anyway.
> 
> Do you have any reference about this?

As PKCS#11 spec lacks timezone information, and as the only other reference is the utcTime, and the fact that the certificate validity dates are copied to CK_DATE, and in order to have a card portable between locations in the worlds, it only makes sense to assume that dates are in UTC. Otherwise when you will travel with your employee card from one country to another you will have different interpretation of the content which will not be in sync with the actual objects such as certificate.

**Comment by ueno** [comment]
That sounds reasonable, thanks for the explanation. @rjrelyea do you think it would make sense to clarify this in the spec?

As for the check itself, however, I still think it is necessary to use `mktime` to catch invalid date (e.g., 2019-06-31).

**Comment by alonbl** [comment]
> As for the check itself, however, I still think it is necessary to use mktime to catch invalid date (e.g., 2019-06-31).

it is still doing so, the better alternative is to use `timegm()`, however, since it is not standard I preferred a simpler fix which you merged.

however, I do not think that the role of PKCS#11 driver is to check anything but standard restrictions which in this case are a month of 01-12 and day of 01-31, any logical error is for enrollment application to manage. This is the same as any business logic of misalignment between attribute and the reality, for example setting a date which is not matching the certificate, or setting different labels for different objects etc...
