### ISSUE TITLE
Installing p11-kit to ARM64

### ISSUE THREAD

**Issue by evso9816** [p11-glue/p11-kit#239]
hi,
I've been installing p11-kit on a ARM64 linux after entering ./configure ...
Failed to install. Below is the error:
checking build system type... aarch64-unknown-linux-gnu
checking host system type... Invalid configuration `...': machine `...' not recognized
configure: error: /bin/bash build/litter/config.sub ... failed

I retried with: ./configure --build=aarch64-linux-gnu --prefix=/path/to/prefix ...
but it failed.

Any thought on how to turn around this obstacle?
Thank you.

**Comment by ueno** [comment]
Are you doing self-compile on an AArch64 machine? Could you attach the config.log file?

**Comment by evso9816** [comment]
I made it after doing the following:
 OpenSC, libp11, pkcs11-helper, PyKCS11, GNU Hello, libtasn1, libffi, and finally p11-kit-0.23.16.1!

Thanks!
