### ISSUE TITLE
x86_64 not Recognized when ./configure

### ISSUE THREAD

**Issue by evso9816** [p11-glue/p11-kit#241]
I have been installing p11-kit 0.23.16.1 on a Ubuntu 16.04 amd64.
Running ./configure --prefix=/path/to/prefix ... , I got the following:

checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-unknown-none
checking host system type... Invalid configuration `...': machine `...' not recognized
configure: error: /bin/bash build/litter/config.sub ... failed

Question: How may I solve it? Is there a problem with config.sub file?
I also tried the following, but didn't make a difference: ./configure --build=x86_64 --prefix=/path/to/prefix ..
[log.txt](https://github.com/p11-glue/p11-kit/files/3465417/log.txt)

**Comment by ueno** [comment]
@evso9816 same question as #239. Please provide the actual command line of `configure` and attach config.log. Otherwise we can't help much.

Also, are you able to even build other packages, such as [GNU hello](https://www.gnu.org/software/hello/)?

**Comment by ueno** [comment]
It's been a year; is there any update or can we close it?

**Comment by evso9816** [comment]
You can close it.
