### ISSUE TITLE
program_invocation_short_name problems with uClibc-ng

### ISSUE THREAD

**Issue by neheb** [p11-glue/p11-kit#268]
I'm getting this error with both meson and autotools with the latest version:

```
../common/compat.c:96:14: error: conflicting types for 'program_invocation_short_name'
 extern char *program_invocation_short_name;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../common/compat.c:48:
/home/mangix/devstuff/openwrt/staging_dir/toolchain-arc_arc700_gcc-8.3.0_uClibc/include/errno.h:54:46: note: previous declaration of 'program_invocation_short_name' was here
 extern const char *program_invocation_name, *program_invocation_short_name;
```

It seems https://github.com/p11-glue/p11-kit/pull/237 was totally wrong.

It seems that a quick git grep shows that meson does not even check for HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME

**Comment by neheb** [comment]
I looked at configure. I see this:

conftest.c:88:10: error: 'program_invocation_short_name' undeclared (first use in this function)
   (void) program_invocation_short_name;

But that's bogus as later on, it gets defines in errno.h : https://github.com/wbx-github/uclibc-ng/blob/860b51c84ac7d763400e7e036f290e3c084dec35/include/errno.h#L54

I tried passing -D_GNU_SOURCE to CFLAGS but it did not work. I don't know why configure is failing on this.

**Comment by ueno** [comment]
It's weird. Is there any easy way to try the compilation on a normal Linux distribution?

**Comment by neheb** [comment]
Not quite sure what you mean. There's an SDK here: http://downloads.openwrt.org/snapshots/targets/arc770/generic/openwrt-sdk-arc770-generic_gcc-8.3.0_uClibc.Linux-x86_64.tar.xz

**Comment by neheb** [comment]
It might be a bug in uClibc-ng. So __USE_GNU is defined in include/features.h , which errno.h seems not to include.

**Comment by neheb** [comment]
Probably no longer relevant. I updated and switched to meson. This problem seems gone.

**Comment by ueno** [comment]
Glad to hear, thanks for the update.
