### ISSUE TITLE
p11-kit server >= 0.23.19 doesn't interoperate with p11-kit-client.so < 0.23.19, breaking Flatpak apps

### ISSUE THREAD

**Issue by smcv** [p11-glue/p11-kit#275]
Distributions that have upgraded to p11-kit 0.23.19 have found that it breaks various Flatpak apps, including Steam and Spotify. More specifically, it breaks certificate trust in libraries and applications inside the runtime if they are linked to p11-kit older than 0.23.19. In particular this affects anything that uses GNUTLS, notably the GNOME stack.

The maintainers of the freedesktop-sdk (org.freedesktop.Platform) base Flatpak runtime seem to be addressing this by upgrading the version inside the runtime to p11-kit 0.23.19, which means this will not be reproducible with newer versions of that runtime, or runtimes like org.gnome.Platform that are based on it. However, it would (I think) continue to be a problem for Flatpak runtimes based on other sources of packages, for example based on Debian 10, or for other containerization frameworks that try to do a similar thing.

For context, if you don't know Flatpak: it's an app containerization framework, which runs a user-facing app like Steam or Spotify in a container. The container's /usr is a "runtime" chosen to match the app, which can be any distribution, but is usually based on a reference runtime called "org.freedesktop.Platform" provided by the freedesktop-sdk project. To make the app work, various things from the host system, like the X11, Wayland, D-Bus and PulseAudio sockets, are made available inside the container, either unrestricted or via a filtering proxy. One of the aspects
of the host system that is injected into the container is p11-kit's idea of the certificates that ought to be trusted.

The structure of what's going on is:

- Outside the container, Flatpak runs the equivalent of:

        p11-kit server --sh -n SOME_PATH --provider p11-kit-trust.so "pkcs11:model=p11-kit-trust?write-protected=yes"

- Flatpak makes the socket SOME_PATH available inside the container it creates, and sets the environment variable `P11_KIT_SERVER_ADDRESS` to its path

- Inside the container, Flatpak writes out
  /etc/pkcs11/modules/p11-kit-trust.module containing:

        # This overrides the runtime p11-kit-trusted module with a client one talking to the trust module on the host
        module: p11-kit-client.so

- The result should be that the p11-kit-client.so module provided by the container runtime talks to the server provided by the host system.

- However, in fact p11-kit-client.so 0.23.18 or older fails to communicate with "p11-kit server" 0.23.19 or newer.

## Steps to reproduce

- Have Flathub as a Flatpak remote, for example:

        flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- Have a Flatpak runtime that does not have p11-kit >= 0.23.19,
  for example at the time of writing this one doesn't:

        flatpak --user install flathub org.freedesktop.Platform//18.08

  (In the version I tested, `/etc/os-release` inside the runtime says
  it's version 18.08.39.)

- Get an interactive prompt in a container with networking enabled:

        flatpak run --command=bash --share=network org.freedesktop.Platform//18.08

- In the container, curl https://example.com

- In the container, gnutls-cli -p 443 example.com

## Expected result

- curl successfully validates example.com's cert
- gnutls-cli successfully validates example.com's cert

## Actual result

- curl successfully validates example.com's cert
- gnutls-cli *does not* successfully validate example.com's cert:
   "Status: The certificate is NOT trusted. The certificate issuer is unknown."

**Comment by smcv** [comment]
More context for the Flatpak feature that shares certificate trust between host and container:

* https://github.com/flatpak/flatpak/pull/1757
* https://github.com/flatpak/flatpak/issues/2721

Bug reports in downstream distributions and dependent packages:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949976
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950096
* https://bbs.archlinux.org/viewtopic.php?id=252390
* https://github.com/flathub/com.valvesoftware.Steam/issues/526
* https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2255
* https://github.com/ValveSoftware/steam-for-linux/issues/6855
* https://forum.manjaro.org/t/update-2020-01-26-has-a-bug/121375
* https://github.com/flathub/com.discordapp.Discord/issues/73

**Comment by smcv** [comment]
Some possible resolutions that I can see:

* If this is not something that's expected to work at all: in Flatpak, stop sharing the p11-kit trust store, and instead use a separate trust store provided by the maintainer of the runtime (this would remove the feature added in flatpak/flatpak#1757)
* If this is something that's expected to work, but only sometimes: in Flatpak, somehow compare the versions of p11-kit on the host and in the container, and only share the trust store if they are "close enough"
* If this is something that's expected to work, regardless of version: in p11-kit, have some sort of capability discovery in the client/server protocol, so that older clients don't get information from newer servers that confuses them, and newer clients cope with incomplete information from older servers

**Comment by ueno** [comment]
We indeed changed the RPC protocol in 0.23.19 as part of #259, so easier workaround would be to revert this change in the p11-kit package on the host. Maybe we should have bumped the protocol version in the header and support both interfaces.

**Comment by smcv** [comment]
> We indeed changed the RPC protocol in 0.23.19 as part of #259, so easier workaround would be to revert this change in the p11-kit package on the host.

Easier for the maintainer of p11-kit on the host, but less easy for everyone else... (although one common workaround people are using is to hold back p11-kit from being upgraded).

> We indeed changed the RPC protocol in 0.23.19 as part of #259

Does that mean containers with p11-kit 0.23.19 also won't interoperate with host systems with 0.23.18? That seems likely to be equally problematic.

The short term response from Flatpak runtime maintainers seems to have been to upgrade all the base runtimes to 0.23.19, but if the resulting runtimes won't work on (for example) Debian 10 and Ubuntu 18.04, that seems counterproductive.

> Maybe we should have bumped the protocol version in the header and support both interfaces.

If it's possible to do that and ship a 0.23.20 with that change, that seems like the best solution.

**Comment by ueno** [comment]
> Does that mean containers with p11-kit 0.23.19 also won't interoperate with host systems with 0.23.18? That seems likely to be equally problematic.

That is true, and it wouldn't be trivial to add compatibility layer in both client and server.
In the meantime I will revert all changes in #259 and release 0.23.20, given that it was proposed to fix a minor corner-case.
