### ISSUE TITLE
'NSS not Initialized' issue with 0.23.20-1

### ISSUE THREAD

**Issue by bitsandnumbers** [p11-glue/p11-kit#278]
Hi,

I found an issue with 0.23.20-1 that is not isolated.

Upgrading from 0.23.19-1 to 0.23.20-1 make Icecat throw an error each time I try to visit a website : 

`An error occurred during a connection to www.google.com. NSS is not initialized. Error code: SEC_ERROR_NOT_INITIALIZED`

The issue was reported there : 
https://aur.archlinux.org/packages/icecat/
https://forum.manjaro.org/t/stable-update-2020-01-30-kernels-browsers-vulkan/121776/91?u=sandy.locke
https://aur.archlinux.org/packages/firefox-wayland-hg/

The fix is to revert back to 0.23.19-1

If you know why this behavior ?

EDIT 1 : I confirm that the issue is also there on 0.23.19-2, so 0.23.19-1 is the latest build working for me.

EDIT 2 : I should mention that it seems to happen only with web browsers compiled with nss-hg

**Comment by ueno** [comment]
I suspect the issues is in somewhere else, as the only change between 0.23.19 and 0.23.20 is [the reversion of a couple of patches](https://github.com/p11-glue/p11-kit/pull/276).

> I should mention that it seems to happen only with web browsers compiled with nss-hg

Are you sure that the package version of nss-hg is not changed during your testing?
Anyway, I would suggest to run icecat under: `P11_KIT_DEBUG=trust MOZ_LOG="certverifier:5"`.

@heftig might have insight on this as this seems to be Arch specific?

**Comment by bitsandnumbers** [comment]
Thanks for the answer.

I suspected NSS-HG package, but on ARCH you have to compile it and I did not compile it for a while (and compiling nss-hg to the latest version does not change anything btw).

I think the right question is : what were the changes between 0.23.19-1 and 0.23.19-2 since 19-2 also break Icecat for me.

I will test to run icecat under: P11_KIT_DEBUG=trust MOZ_LOG="certverifier:5" as you suggest.

**Comment by heftig** [comment]
@ueno Could the distrust-after changes break compatibility with NSS versions that don't support these attributes?

**Comment by bitsandnumbers** [comment]
Running Icecat with options P11_KIT_DEBUG=trust MOZ_LOG="certverifier:5" does not seem to change anything... I also tested with a blank profile, but still.

**Comment by heftig** [comment]
Ah, never mind.

> I think the right question is : what were the changes between 0.23.19-1 and 0.23.19-2 since 19-2 also break Icecat for me.

This is the change in 0.23.19-2: https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/p11-kit&id=91cfae5c17785fe92877c9a49568f1664c0dcf19

We dropped a patch that built `/usr/lib/libnssckbi-p11-kit.so`, a hacked version of `p11-kit-trust.so` which renamed the default trust module's name and label to look like a normal `libnssckbi.so`'s "Builtin Object Token".

At the same time, our NSS was changed to use `p11-kit-trust.so` as `libnssckbi.so` instead: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nss&id=9f258a64e4366be54a6c61a9acd77ab65c4c9ad7

**Comment by heftig** [comment]
`nss-hg` is broken as it now links `libnssckbi.so` to the nonexistent `libnssckbi-p11-kit.so`.

**Comment by bitsandnumbers** [comment]
So I should point nss-hg devs to this issue maybe ?

**Comment by ueno** [comment]
Thanks @hetfig for the explanation. I'm closing this for now.
