### ISSUE TITLE
firefox is very slow and crashes because of p11-kit-proxy.so

### ISSUE THREAD

**Issue by stsp** [p11-glue/p11-kit#287]
When I insert the eToken, in firefox
security devices I can see it under p11-kit-proxy.
It is identified as "SafeNet eToken 5100 [eToken 5110 SC] 00 00".
The problem is that the "Security devices" menu
then loads over a minute. If I remove token, firefox
crashes. If I remove p11-kit-proxy by clicking Unload
in firefox menu, it crashes too.
The biggest problem is that firefox became very
slow at opening sites. It actually can't open most
of them while the token is inserted, but if you hit
Reload many times, maybe you get lucky to open
something. I actually thought there are problems
with my ISP... But no, the problem appeared to be
with p11-kit.
But if the token is not inserted, none of the above
problems happen. Firefox is blazingly fast, I can
enter the Security devices menu instantly, and
Unloading p11-kit-proxy does not lead to a crash.

**Comment by ueno** [comment]
Are you saying that it doesn't happen if you manually register the "SafeNet" device under "Security devices" menu, or automatic registration of p11-kit-proxy *is* a problem?

If the latter, you can always opt-out by writing a [module configuration file with `disable-in: firefox`](https://p11-glue.github.io/p11-glue/p11-kit/manual/pkcs11-conf.html). If the former, please provide the details of your setup, including the versions of p11-kit, firefox, and nss.

**Comment by stsp** [comment]
> devices" menu, or automatic registration of p11-kit-proxy is a problem?

Automatic.
I didn't do anything, and that's the biggest
problem. Out of sudden your internet is slow.

> If the latter, you can always opt-out by writing a module configuration file with disable-in: firefox.

I created `/etc/pkcs11/pkcs11.conf` with this content:
```
module: p11-kit-proxy.so
disable-in: firefox
```
and restarted firefox.
Nothing changed, I can still see p11-kit-proxy.so
in security devices.
Anyway, why would I do that?
Do you really think that the user should
get the slow internet until he creates some
magic file somewhere?

**Comment by ValZapod** [comment]
Was fixed in https://salsa.debian.org/rousseau/PCSC/-/commit/05d48e5c13305d3772d147a95a5f73cc10079147

**Comment by stsp** [comment]
Not quite.
Many people tried to help, another
example is this:
https://github.com/OpenSC/OpenSC/issues/2030
But the performance issue was only
mildly improved, and the crash problem
won't advance w/o p11-kitt ppl involvement,
which seems unlikely judging by the
"Invalid" mark on that report.
I think the only possibility is to ask
fedora to stop auto-loading p11-kit-proxy,
as this is what the vanilla firefox doesn't
do anyway.

**Comment by stsp** [comment]
It crashes here:
```
#0  0x00007fffc9601339 in proxy_C_GetSlotInfo (self=<optimized out>, 
    id=<optimized out>, info=0x7fffe78bcc38) at ../p11-kit/proxy.c:538
538		return (map.funcs->C_GetSlotInfo) (id, info);
(gdb) p map.funcs->C_GetSlotInfo
```

So even though I'll keep reporting bugs
to other projects to at least get some
work-around, the problem is in p11-kit.

**Comment by ueno** [comment]
@stsp open source projects are run by volunteers. Could you stop taking such a harsh tone when reporting issues, please?

**Comment by stsp** [comment]
OK, sorry, will do.
I was very bored after "fighting" a
slow internet for a few weeks, which
happened to be the p11-kit problem
at the end. :) That involved the request
of ISP change, problems at work as
I couldn't work remotely (in coronavirus)
and all that. So I was really tired, sorry.
But marking report as Invalid w/o
a bit of explanation, is also a bit harsh.

**Comment by ValZapod** [comment]
@ueno Thank you for the project )) @stsp Does Chromium support all of it? Can you check it there? IMHO, Firefox should handle it! Also did you check debian, is that the same case there? Check testing, please.

**Comment by stsp** [comment]
Yes, when I tried Chromium, that was
a turning point. I suddenly realized that
my ISP is not slow. :)
Chromium works very well, yes.
AFAIK it doesn't use p11-kit, but I may
be wrong on that.

**Comment by stsp** [comment]
@ValZapod whether it works on debian,
depends on just one thing: does debian
change firefox to auto-load p11-kit, as
does fedora? If it doesn't do that, then
there is no such problem for sure.
Problem is fedora-specific so far.

**Comment by ValZapod** [comment]
Well, first, did you test it with commit https://github.com/p11-glue/p11-kit/commit/c8f8053edc9098fdb36fbb34165b8d92ed596798? It changes that file. Second, map.funcs->C_GetSlotInfo here we do dereference *(map.funcs).C_GetSlotInfo, so... one of the pointers is invalid there?

**Comment by stsp** [comment]
> Well, first, did you test it with commit c8f8053? 

I am actually trying to do that right
now, but can't build p11-kit-proxy.so.
I cloned the repo, configured, it build
many p11 libs, but no proxy lib.
How can I build it?

> map.funcs->C_GetSlotInfo here we do dereference *(map.funcs).C_GetSlotInfo,
> so... one of the pointers is invalid there?

"map" is also corrupted:
```
(gdb) p map
$2 = {wrap_slot = 1, real_slot = 140736140246648, funcs = 0x2000500000003}
```
Note that this happens after eToken
is unplugged. I think p11-kit just frees
everything, and here we are walking
the chain of freed pointers.

**Comment by stsp** [comment]
OK, I realized that p11-kit-proxy.so and libp11-kit.so
is the same thing. :)
So lets see with the commit you mentioned...

**Comment by stsp** [comment]
OK, I replaced /usr/lib64/libp11-kit.so.0.3.0
with the freshly built one, but it doesn't see
the token at all.
I suppose not only this file needs to be replaced?

**Comment by stsp** [comment]
I.e. I can do "sudo make install", but
I am not sure how good it will be to have
both rpm and local build installed.

**Comment by stsp** [comment]
No, even after "sudo make install"
and specifying /usr/local/lib/p11-kit-proxy.so
in firefox, it still doesn't see the token.

**Comment by ValZapod** [comment]
Check the symlink? Dunno))

**Comment by ValZapod** [comment]
p11-kit-proxy.so should be a symlink to libp11-kit.so.0.3.0

**Comment by stsp** [comment]
Yes, the link is fine.
firefox wouldn't load bad symlink
or a wrong lib.
So its something else here.
Currently trying to go to the past
with git to see if some change
affected that.

**Comment by stsp** [comment]
Well, no matter how far I go down
the git tree, it doesn't see my eToken...
The last hope is to build the fedora
version. Maybe they allied some patch...

**Comment by stsp** [comment]
OK, no solution.
Building via rpm works (as to seeing
the token), building the same sources
w/o rpm - doesn't.
But rpm uses meson to build, not
autotools! How can I replicate the
same build w/o rpm? :(

**Comment by ValZapod** [comment]
Apply only that commit on top?

**Comment by stsp** [comment]
rpm appears to have no extra patches.
But it has the entirely different build process. :(
Possibly with autotools I could get the
same results by passing some magic flags
to configure, but its hard to figure out.

**Comment by stsp** [comment]
Or you mean, apply that commit from
git and re-build with rpm?

**Comment by stsp** [comment]
OK, I think I managed to replicate the
rpm build with the following commands:
```
meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . x86_64-redhat-linux-gnu -Dgtk_doc=true -Dman=true -Dtrust_paths=/etc/pki/ca-trust/source:/usr/share/pki/ca-trust-source

ninja -v -j8 -C x86_64-redhat-linux-gnu
```

as that's what rpmbuild is executing.

**Comment by stsp** [comment]
OK, I confirm that there is no crash any
more, and the commit you point to, is the
one responsible for a fix (I tried reverting
it).
So now only the huge slowdowns remain.
But this may not be the problem of p11-kit.
When will the commit you mentioned, appear
in fedora?

**Comment by stsp** [comment]
Still, how to properly build this with
autotools? Its crazy that I had to rip
the meson commands from rpmbuild.

**Comment by ValZapod** [comment]
> When will the commit you mentioned, appear
> in fedora?

You need to write to them.

What about "I also suspect that p11-kit-proxy.so is bogus and does stupid things like calling C_GetSlotList() every second. I never used this software p11-kit" from @LudovicRousseau? Can @ueno you comment? Please. 🤔🤔

**Comment by stsp** [comment]
This was likely the wrong spot.
In fact, here's the log:
https://bug1627273.bmoattachments.org/attachment.cgi?id=9147025
It shown that p11-kit returns CKR_TOKEN_NOT_PRESENT
instead of CKR_TOKEN_NOT_RECOGNIZED, just as
opensc did before the fix.

**Comment by ValZapod** [comment]
Oh! So https://github.com/p11-glue/p11-kit/blob/a96af650e1ac2f5faecc9354ac30d128a7e93b9f/common/mock.c#L676 this should be CKR_TOKEN_NOT_RECOGNIZED somewhere?

**Comment by stsp** [comment]
Yes, like in this log:
https://github.com/OpenSC/OpenSC/files/4652623/logfile.new.txt

**Comment by stsp** [comment]
The problem is that my token is not
recognized by these libs. But firefox
doesn't know that, as they return wrong
status.

**Comment by stsp** [comment]
See https://github.com/OpenSC/OpenSC/commit/16456922e2a038ae38f58cffaa7696013a761b3b
for the reference.

**Comment by ValZapod** [comment]
Wait a second. OpenSC is not updated including that commit https://github.com/OpenSC/OpenSC/commit/16456922e2a038ae38f58cffaa7696013a761b3b when you compile p11-kit?? Of course it will not work, as p11-kit is using OpenSC in full!

**Comment by stsp** [comment]
Yes, you are right, opensc is not updated
in fedora yet. :(

**Comment by ValZapod** [comment]
Report it here)) https://bugzilla.redhat.com/buglist.cgi?quicksearch=OpenSC
Lets close it. After all, I think Firefox will work correctly.

**Comment by stsp** [comment]
OK, lets do.

**Comment by ValZapod** [comment]
Any updates?

**Comment by ValZapod** [comment]
@stsp BTW, did you see https://github.com/OpenSC/OpenSC/issues/1999? Looks dangerous))

**Comment by stsp** [comment]
Looks windows-specific.

**Comment by fdelapena** [comment]
I'm also getting this slow issue in Fedora, but not in other distros where I replace the libnssckbi.so with p11-kit-proxy.so, so maybe the issue is Fedora specific due to crypto consolidation configuration and settings, maybe has more to do with NSS than p11-kit.
And not related with OpenSC, happening here with a proprietary .so middleware.
Not crashing here anymore, so the mentioned here were likely unrelated.

For some reason Firefox on Fedora insists on accessing the token for every TLS request (refreshing http sites without cache don't trigger it), feels like using the RNG or whatever else, still not tested what and why is being called. Unplugging the token (from a card reader) is enough to get navigation fast again.

**Comment by stsp** [comment]
I also have to admit that the problem
is not fully fixed.
Please see the upstream report I created:
https://bugzilla.mozilla.org/show_bug.cgi?id=1627273
which is unfortunately also closed by now.
In fact, I am even still experiencing the
crashes sometimes, when unloading
p11-kit-proxy in firefox GUI:
https://crash-stats.mozilla.org/report/index/73febf93-f829-4312-8ee6-fd53a0211208
even though they are now much rare
than before.
And the slow-down problem was only
mildly amended.
