### ISSUE TITLE
Document configure flags needed for non-root installations?

### ISSUE THREAD

**Issue by anjohnson** [p11-glue/p11-kit#295]
I was using the sources from the p11-kit-0.23.20 tarfile, building on a RHEL-7.8 system (RedHat deliberately remove the remote client and server from their packaging of p11-kit before RHEL-8). I found out the hard way that a non-root `make install` only works if you specify the flags `--without-bash-completion --without-systemd` to `./configure --prefix=$HOME/prefix`. It would be nice to document these flags and mention their requirement for non-root installations somewhere (say in the README).

Love the functionality of this tool (although it would be nice to not have to install gnutls just to get the token URL from my PIV card, could that be automated in the server somehow?).

**Comment by ueno** [comment]
Thanks for the report; I'm going to mention that in the build instruction added as part of #296.

> although it would be nice to not have to install gnutls just to get the token URL from my PIV card, could that be automated in the server somehow?

Indeed, maybe we could expand `p11-kit list-modules` output (or add `p11-kit list-tokens` subcommand).
