### ISSUE TITLE
Add strings like "Default Trust" to translations

### ISSUE THREAD

**Issue by scootergrisen** [p11-glue/p11-kit#297]
For GNOME i translate Passwords and Keys.

In the main window i see "Default Trust". Maybe from https://github.com/p11-glue/p11-kit/blob/daf1a84de39c4cdbd308c6a0b80b437689a222c7/trust/test-module.c#L388
I would like strings that are very visible for the user to be translatable so i can give the user a more complete translation experience.

So maybe such strings could be added to the translations.

**Comment by ueno** [comment]
I'm afraid doing that in p11-kit might be complicated, because in the PKCS#11 spec module name must fit in 32-bytes buffer without null-termination. I suggest doing that in Seahorse instead, if possible.

**Comment by scootergrisen** [comment]
ok
