### ISSUE TITLE
trust anchor --remove doesn't print any output or change exit code on failure

### ISSUE THREAD

**Issue by nmav** [p11-glue/p11-kit#300]
p11-kit-0.23.20:
```
# trust anchor --remove 'pkcs11:id=%AD%6C%AA%94%60%9C%ED%E4%FF%FA%3E%0A%74%2B%63%03%F7%B6%59%BF;type=cert'
```
Exit code is zero and no error is printed. When run with verbose it prints that the certificate was not removed.

p11-kit-0.23.2:
```
# trust anchor --remove 'pkcs11:id=%AD%6C%AA%94%60%9C%ED%E4%FF%FA%3E%0A%74%2B%63%03%F7%B6%59%BF;type=cert'
p11-kit: couldn't remove read-only certificate
```
Exit code is again zero but an error message is printed.

I think the expected behavior on failure would be to print a message and set an error code.

**Comment by ueno** [comment]
This is a regression after #84 (yours :-). Maybe, all the tools provided by the p11-kit package should call `p11_message_loud`.

**Comment by nmav** [comment]
I certainly do many mistakes :) Makes sense to me. Returning an error would also be useful for scripting these tools.
