### ISSUE TITLE
/usr/local/lib/pkcs11 symlink

### ISSUE THREAD

**Issue by LiborCH** [p11-glue/p11-kit#302]
Homebrew creates a symlink /usr/local/lib/pkcs11 -> ../Cellar/p11-kit/0.23.12/lib/pkcs11 that disallows to use another pkcs11 middleware aside of p11-kit because the pkcs11 is not a directory in but symlink somewhere. Better to create /usr/local/lib/pkcs11 directory and then create symlinks for libraries one by one.

**Comment by ueno** [comment]
I think it'd be better reported to homebew, as it's not under control of the p11-kit installation process.

**Comment by ueno** [comment]
Closing for now as a downstream issue. Feel free to reopen if we can be of any help in this regard.
