### ISSUE TITLE
Problems finding secret keys

### ISSUE THREAD

**Issue by bgermann** [p11-glue/p11-kit#320]
Using the iter API, I try to enumerate the objects on a softhsm2 token. None of the objects with CKO_SECRET_KEY class (holding AES keys) are found. Other objects are found.

**Comment by ueno** [comment]
CKO_SECRET_KEY objects are usually hidden until the user is authenticated. Are you logged in to the token?

**Comment by bgermann** [comment]
I see. Is there any example how to login?

**Comment by ueno** [comment]
I don't have a complete example, but you could do something like:
1. initialize a module using `p11_kit_module_initialize` or something
1. open a session with `module->C_OpenSession`
1. login to the session with `module->C_Login`
