### ISSUE TITLE
meson: doc/manual/pkcs11.conf.5 has problems with userdir/sysdir expansions

### ISSUE THREAD

**Issue by t184256** [p11-glue/p11-kit#332]
`doc/manual/pkcs11.conf.5` has `<literal>&sysdir;/pkcs11.conf</literal>` expanded to `etc/pkcs11 /pkcs11\&.conf` (notice the space in the variable expansion)

I see that `doc/manual/Makefile.am` uses `echo -n` to generate the intermediate files with the values, this might be a relevant nuance lost during the transition to meson.

**Comment by ueno** [comment]
Indeed; we'll probably have to use the [`command` keyword](https://mesonbuild.com/Reference-manual.html#configure_file), or rewrite it with a custom target to avoid the trailing newline.
