### ISSUE TITLE
__STDC_VERSION__ used but may not be defined

### ISSUE THREAD

**Issue by dirkf** [p11-glue/p11-kit#337]
[Here](https://github.com/p11-glue/p11-kit/blob/8e58477c68c77ef2c29a3fc7d728220929c0996f/common/compat.h#L55) the macro `__STDC_VERSION__` is used, which may [not be defined if the C compiler defaults to an old standard](https://sourceforge.net/p/predef/wiki/Standards/).

Either `#if ((defined(__STDC_VERSION__) && 201112L <= __STDC_VERSION__) \`, or have `configure` ensure that the compiler is configured for a sufficiently recent standard level (say C99), with an option like `-std=c99` if necessary.

**Comment by ueno** [comment]
Thank you for the report; let's take the former approach.
