### ISSUE TITLE
fatal error: basic.asn.h: No such file or directory

### ISSUE THREAD

**Issue by tropikhajma** [p11-glue/p11-kit#348]
My build fails with
...
gmake[2]: Entering directory '/builds/pheimlic/p11-kit/components/desktop/p11-kit/build/i86'
/usr/gcc/10/bin/gcc -DHAVE_CONFIG_H -I. -I/builds/pheimlic/p11-kit/components/desktop/p11-kit/p11-kit-0.23.22  -I/builds/pheimlic/p11-kit/components/desktop/p11-kit/p11-kit-0.23.22 -I/builds/pheimlic/p11-kit/components/desktop/p11-kit/p11-kit-0.23.22/common -DBINDIR=\"/usr/bin/i86\" -DBUILDDIR=\"/builds/pheimlic/p11-kit/components/desktop/p11-kit/build/i86\" -DDATA_DIR=\"/usr/share\" -DPRIVATEDIR=\"/usr/lib/p11-kit\" -DSRCDIR=\"/builds/pheimlic/p11-kit/components/desktop/p11-kit/p11-kit-0.23.22\" -DSYSCONFDIR=\"/etc\" -DP11_KIT_FUTURE_UNSTABLE_API -m32 -DP11_KIT_FUTURE_UNSTABLE_API   -m32  -O3 -mincoming-stack-boundary=2  -ffile-prefix-map=/builds/pheimlic/p11-kit/components/desktop/p11-kit=.    -g             -Wall -Wstrict-prototypes -Wmissing-declarations                -Wmissing-prototypes -Wnested-externs -Wpointer-arith           -Wdeclaration-after-statement -Wformat=2 -Winit-self            -Waggregate-return -Wno-missing-format-attribute                -fno-strict-aliasing -fno-common -Wmissing-include-dirs -Wundef -MT trust/trust-persist.o -MD -MP -MF trust/.deps/trust-persist.Tpo -c -o trust/trust-persist.o `test -f 'trust/persist.c' || echo '/builds/pheimlic/p11-kit/components/desktop/p11-kit/p11-kit-0.23.22/'`trust/persist.c
/builds/pheimlic/p11-kit/components/desktop/p11-kit/p11-kit-0.23.22/trust/persist.c:51:10: fatal error: basic.asn.h: No such file or directory
   51 | #include "basic.asn.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [Makefile:4485: trust/trust-persist.o] Error 1
gmake[2]: Leaving directory '/builds/pheimlic/p11-kit/components/desktop/p11-kit/build/i86'
gmake[1]: *** [Makefile:4811: all-recursive] Error 1
gmake[1]: Leaving directory '/builds/pheimlic/p11-kit/components/desktop/p11-kit/build/i86'
gmake: *** [Makefile:2356: all] Error 2

0.23.20 built fine, I guess it's related to https://github.com/p11-glue/p11-kit/commit/adbb94ea3ec3c39b71c05eff8ef86cc85a075955

I had to use the attached patch to fix it: [03-trust.patch.txt](https://github.com/p11-glue/p11-kit/files/5855830/03-trust.patch.txt)

This is on Solaris 11.4

**Comment by ueno** [comment]
Thank you for the report; this is indeed a regression. It should be fixed with #353.
