### ISSUE TITLE
Building URIs with from CK_TOKEN_INFO

### ISSUE THREAD

**Issue by brandon1024** [p11-glue/p11-kit#356]
An internal project I maintain uses p11-kit to parse the fields from a PKCS#11 URI. This has worked really well for me so far, but I've started working on an enhancement where I need to build some URIs and I have found the p11-kit API a bit lacking, either in documentation or feature set.

After enumerating tokens on a smartcard and picking a specific object in that slot, I need to generate a URI that looks (roughly) like this:
```
pkcs11:model=PKCS%2315;manufacturer=www.atos.net%2Fcardos;serial=424D414B504A5941;token=Siemens%20Corporate%20ID%20Card%20%28V8%29;id=%34%35%B7%6A%9E%B3%B8%FE%CE%0B%60%2D%E4%65%BA%BF%C0%D9%61%60;object=Auth%2027.04.20%2014%3A49%3A31%20-%2027.04.22;type=cert
```

I have a `CK_TOKEN_INFO` with the information needed to set the `model`, `manufacturer`, `token` and `id` fields of the URI, but I can't seem to figure out how to set these using the p11-kit URI API.

Maybe the API does support this, but I just don't see it? I read through the documentation a few times and couldn't seem to figure it out how to do it.

Ideally I could supply a pointer to the `CK_TOKEN_INFO` structure and p11-kit would update its context with the valid fields. Is this reasonable?

Thanks for your time!

**Comment by brandon1024** [comment]
Should `p11_kit_uri_set_attributes ()` be used?

**Comment by ueno** [comment]
After creating a `P11KitUri` object, you can obtain a reference to `CK_TOKEN_INFO` in it and modify the relevant fields; see [this test](https://github.com/p11-glue/p11-kit/blob/master/p11-kit/test-uri.c#L510) for example.

**Comment by brandon1024** [comment]
@ueno Oh interesting, I wouldn't have thought to do that. That's perfect, thank you!
