### ISSUE TITLE
Weird situation around internationalization

### ISSUE THREAD

**Issue by ericonr** [p11-glue/p11-kit#357]
I am switching p11-kit to use the meson build system instead of autotools, which changed a few things. First, autotools seems to never want to install the files from `po/`, so the package doesn't ship any of them. Switching to meson was enough for them to be properly generated and installed.

However, I can't figure out how you are *using* the files...

This block, from `messages.c`, is never enabled (`ENABLE_NLS` and `PACKAGE_NAME` aren't defined):

```
#ifdef ENABLE_NLS
#include <libintl.h>
#define _(x) dgettext(PACKAGE_NAME, x)
#else
#define _(x) x
#endif
```

but even if it were, the necessary `textdomain` call to initialize gettext doesn't exist anywhere. If you can guarantee the toolchain supports a constructor, you can put it there, though I'm not sure how it behaves if called before `setlocale`, which also isn't called anywhere here.

For now, at least, it seems like enabling `nls` only generates files which aren't used by any part of the resulting package :/

**Comment by ueno** [comment]
Thank you for pointing that out. I've filed #358 to fix this as well as to make more strings translatable (it might be too much though).
