### ISSUE TITLE
JKS Reproducible results?

### ISSUE THREAD

**Issue by dafanasiev** [p11-glue/p11-kit#379]
It is possible to get **reproducible** results for `p11-kit extract` for `jks` format for same inputs?
Now docker/oci images that update ca-certs (for example based on RHEL8) cant be "cached" (event, when no ca certs changed from built to build), because p11-kit cli produce different results jks file every time.

Note: settup `SOURCE_DATE_EPOCH` env not fix this behavior.

**Comment by winner658** [comment]
@dafanasiev 
By looking at the code, you can find that
/*
	 * We use the current time for each entry. Java expects the time
	 * when this was this certificate was added to the keystore, however
	 * we don't have that information. Java uses time in milliseconds
	 */
This means that JKS generation is timestamp-dependent. If you want to generate the same JKS, you may need to specify a fixed time.

`if (_p11_extract_jks_timestamp)
		now = _p11_extract_jks_timestamp;
	else { ... ...`

`/* The creation date: current time */
		add_msb_long (buffer, now);`

**Comment by ueno** [comment]
This should be already fixed by #418. It would be nice if you could try to reproduce the issue with the patch and the `SOURCE_DATE_EPOCH` envvar setup.

**Comment by heftig** [comment]
Does Java actually care about the timestamps?

If it doesn't, wouldn't it make sense to simplify the code and always use `_p11_extract_jks_timestamp`, so outside of tests, `0` is used?

If it does, maybe p11-kit could use the mtimes of the trust-source files that contain the certificates instead of the current time?
