### ISSUE TITLE
Use plural-form string in "%u error while processing"

### ISSUE THREAD

**Issue by rffontenelle** [p11-glue/p11-kit#380]
[trust/anchor.c](/p11-glue/p11-kit/blob/master/trust/anchor.c) has the following block starting in line 699:

```
	if (errors > 0) {
		if (errors == 1)
			p11_message (_("%u error while processing"), errors);
		else
			p11_message (_("%u errors while processing"), errors);
```

While this is OK for English and some languages, it can be very problematic for other languages with more than one plural form. Please consider using `ngettext()` for leaving to GNU Gettext to generate plural strings for translators. See [TranslationProject/DevGuidelines/Plurals on GNOME Wiki](https://wiki.gnome.org/TranslationProject/DevGuidelines/Plurals) and [Additional functions for plural forms in GNU Gettext Manual](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html).

**Comment by ueno** [comment]
Thanks! Fixed through #381.
