### ISSUE TITLE
"trust dump --help" displays "usage: trust list"

### ISSUE THREAD

**Issue by nora-pxh** [p11-glue/p11-kit#413]
"trust dump --help" displays usage of trust list incorrectly.
The usage string of p11_tool_desc usages in trust/dump.c uses “trust list”.
	p11_tool_desc usages[] = {
		{ 0, "usage: trust list --filter=<what>" },

**Comment by winner658** [comment]
The usage string of p11_tool_desc usages in trust/dump.c  should  uses "trust dump" 
p11_tool_desc usages[] = {
{ 0, "usage: trust dump--filter=" },

**Comment by winner658** [comment]
i think it was copy from trust/list.c, and author forget changed

**Comment by ueno** [comment]
Yes, pull-request fixing it would be welcome :-)

**Comment by ueno** [comment]
Should be fixed in #414.
