### ISSUE TITLE
Compat definitions of O_BINARY and O_CLOEXEC broken

### ISSUE THREAD

**Issue by kadler** [p11-glue/p11-kit#425]
https://github.com/p11-glue/p11-kit/blob/master/common/compat.h#L78-L84

compat.h does not include fcntl.h, so the definitions of O_BINARY and O_CLOEXEC will never be defined already unless one of the includers of compat.h includes fcntl.h first (which AFAICT is never the case). This will cause O_BINARY and O_CLOEXEC to always be defined to 0 and then when fcntl.h is included, they will either get overridden by the system headers or left as 0 instead of using the system values if the system values are guarded by an ifndef (not sure any systems do this though).

Seems like compat.h should include fcntl.h before it checks whether these are defined.

**Comment by ueno** [comment]
Thank you for the report. It should be fixed with #428.
