### ISSUE TITLE
test-managed failed

### ISSUE THREAD

**Issue by jkr1987** [p11-glue/p11-kit#466]
hello i'm trying to build p11-kit on ubuntu 22

when i run : 
`$ meson test -C _build`

that give me :

```
=================================== 27/33 ====================================
test:         test-managed
start time:   13:51:51
duration:     0.21s
result:       killed by signal 6 SIGABRT
command:      MALLOC_PERTURB_=13 /home/p11-kit/_build/p11-kit/test-managed
----------------------------------- stderr -----------------------------------
p11-kit: 'result != NULL' not true at p11_virtual_wrap
==============================================================================
```

Thankful for any wise thoughts.

**Comment by ueno** [comment]
Thank you for the report. I can reproduce if I compile p11-kit without libffi, even with an increased number of closures. We probably should exercise the configuration in the CI as well.

**Comment by jkr1987** [comment]
tank you ! i installed libffi and that works !
