### ISSUE TITLE
Test p11-kit Proxy

### ISSUE THREAD

**Issue by jkr1987** [p11-glue/p11-kit#468]
Hello, i have just build and install p11-kit and i'm trying to test the proxy with a simple pkcs11 program or p11-kit list-modules

`# meson install -C _build`
didn't create any configuration file. 
So i created ~/.config/pkcs11/pkcs11.conf
`user-config:only`
 
~/.config/pkcs11/modules/softhsm.conf 
```
module:/usr/lib/libsofthsm2.so
critical:yes
```

and ~/.config/pkcs11/modules/cryptokihsm.conf 
```
module:/usr/local/lib/opencryptoki/libopencryptoki.so
critical:yes
```

when i try test it
```
$ echo $PKCS11_PROXY_MODULE
/usr/local/lib/x86_64-linux-gnu/p11-kit-proxy.so
```
```
$ p11tool --list-tokens --provider=$PKC11_PROXY_MODULE
Segmentation fault (core dumped)

```
```
$ p11-kit list-modules
```
works and display all token of my both softHSM

I don't know if load p11-kit-proxy.so to use it like a p11 provider is the right way.

Thankful for any wise thoughts.

**Comment by jkr1987** [comment]
now i have seg fault
```
p11tool --list-tokens --provider=$PKCS11_PROXY_MODULE
Segmentation fault (core dumped)
```

**Comment by ueno** [comment]
`p11tool` already links to `libp11-kit.so`, which is the same binary as `p11-kit-proxy.so`, so you don't need to specify it with `--provider`, though it shouldn't crash with segmentation fault.

**Comment by jkr1987** [comment]
ok thanks !
