### ISSUE TITLE
RPC module: `InitToken` `pLabel` parameter differs from spec

### ISSUE THREAD

**Issue by uhhhh2** [p11-glue/p11-kit#497]
According to [5.5.7 C_InitToken](https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/cs01/pkcs11-spec-v3.1-cs01.html#_Toc111203268): 

```
CK_DECLARE_FUNCTION(CK_RV, C_InitToken)(
      CK_SLOT_ID slotID,
      CK_UTF8CHAR_PTR pPin,
      CK_ULONG ulPinLen,
      CK_UTF8CHAR_PTR pLabel
);
```

> `C_InitToken` initializes a token. `slotID` is the ID of the token’s slot; `pPin` points to the SO’s initial PIN (which need not be null-terminated); `ulPinLen` is the length in bytes of the PIN; `pLabel` points to the 32-byte label of the token (which MUST be padded with blank characters, and which MUST NOT be null-terminated). This standard allows PIN values to contain any valid UTF8 character, but the token may impose subset restrictions.

From the above description, the `pLabel` is a 32-byte space padded string. However, the ~~proxy~~ RPC module seems to be using the `zero_string` functions rather than `space_string` functions for the `pLabel`

**Comment by ueno** [comment]
Thank you for the report. I'm a bit confused because the proxy module doesn't impose any string representation behind the pointer. Do you perhaps mean RPC rather than the proxy module?

**Comment by uhhhh2** [comment]
yes, RPC.
