### ISSUE TITLE
`p11-kit export-object` should be able to export public key

### ISSUE THREAD

**Issue by ZoltanFridrich** [p11-glue/p11-kit#546]
Currently `p11-kit export-object` can only export certificates, while p11tool (GnuTLS) is capable of exporting public key objects (CKO_PUBLIC_KEY) with the `--export-pubkey` option. `p11-kit export-object` could also support it.

**Comment by ueno** [comment]
@ZoltanFridrich I decomposed this to 3 individual issues (this, #565, and #566), as the others are rather larger tasks.
