### ISSUE TITLE
On PPC Tiger, old Mac OS X 10.4.11, test target does not build with GCC 4.2

### ISSUE THREAD

**Issue by ballapete** [p11-glue/p11-kit#649]
Hello!

Other compiler option would be GCC 7.5.

Version of p11-kit is 0.25.5.

The problem is that CK_ULONG and CK_SESSION_HANDLE get redefined. I prepared the attached patch set. With it applied the default and the test target build.

See also: https://trac.macports.org/ticket/70399.

--

Pete

[Patches-for-test-target-on-Tiger.diff.zip](https://github.com/user-attachments/files/16321420/Patches-for-test-target-on-Tiger.diff.zip)

**Comment by ueno** [comment]
Thank you for the report; it indeed looks like a bug. I've filed #653 to fix it.
