### ISSUE TITLE
nginx hangs

### ISSUE THREAD

**Issue by gfrankliu** [p11-glue/p11-kit#65]
This is continuation of https://github.com/OpenSC/libp11/issues/156

@nmav I'm already using the latest p11-kit with latest centos 7. I did a yum update and no new updates. Or do you suggest I uninstall that and build my own from github? I know there are a few other centos packages dependent on p11-kit. If I replace it with latest from github, will they be compatible ?

**Comment by nmav** [comment]
Yes, try the latest _released_ p11-kit, not the one available in centos.

**Comment by gfrankliu** [comment]
Tried 0.23.5. nginx no longer hangs, but ssl fails to negotiate
```
curl -kv https://localhost
* About to connect() to localhost port 443 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -5938 (PR_END_OF_FILE_ERROR)
* Encountered end of file
* Closing connection 0
curl: (35) Encountered end of file
```

Here is from nginx error log:
```
2017/04/25 15:15:16 [crit] 9959#0: *1 SSL_do_handshake() failed (SSL: error:80003005:Vendor defined:PKCS11_check_token:General Error error:1409B006:SSL routines:SSL3_SEND_SERVER_KEY_EXCHANGE:EVP lib) while SSL handshaking, client: 127.0.0.1, server: 0.0.0.0:443
```

When I add back below two lines to nginx.conf, it starts working again.
```
master_process off;
daemon off;
```

**Comment by nmav** [comment]
I've never used softtokn and I don't know how it handles process forking. I'd suggest using softhsm or a smart card for testing.

**Comment by gfrankliu** [comment]
I am using softhsm for testing, as mentioned in the first post of the original ticket. Not sure where you got softtokn

**Comment by gfrankliu** [comment]
I think I found the issue. I have to do `sudo chown -R nginx_user /var/lib/softhsm` . 
nginx starts as root, but then downgrades as non-root user. Since the forked process is not root, it can't read the softhsm even though the master nginx process runs as root. Once I've done chown, it starts working with latest p11-kit 0.23.5. Is this expected behavior?

**Comment by mouse07410** [comment]
Yes. This is a SoftHSMv2 problem. I reported that bug to SoftHSMv2 crowd, and they said it works as expected.

My solution (on Mac, something similar got to exist on Linux) was to create `~/.config/softhsm2/softhsm2.conf` file and `~/.config/softhsm2/tokens/` directory.
```
$ cat ~/.config/softhsm2/softhsm2.conf 
# SoftHSM v2 configuration file

directories.tokendir = /Users/mouse/.config/softhsm2/tokens/
objectstore.backend = file

# ERROR, WARNING, INFO, DEBUG
log.level = INFO
$ 
```

See if it helps your problem.

**Comment by gfrankliu** [comment]
That works though in my normal setup, nginx runs as "nobody" which has home dir in / by default.
```
grep nobody /etc/passwd
nobody:x:99:99:Nobody:/:/sbin/nologin
```

**Comment by ueno** [comment]
Can we close this?  Is there anything we can do from the p11-kit side?
