### ISSUE TITLE
Flatpak support for read-only per user p11-kit remote socket

### ISSUE THREAD

**Issue by alexlarsson** [p11-glue/p11-kit#68]
I have been looking at the ca-certificate story for flatpak. Currently each runtime ships a ca-certificatates bundle and is set up to use that. However, that is basically wrong, what we want to do is expose the ca-certs from the host (in a read-only fashion). I looked into exporting the raw files, but it seems like every distro is doing things in their own way, so this seems pretty painful.

Instead we could rely on the host shipping with p11-kit, and bind-mount a unix socket into the sandbox in a well known location (this is how we expose X11/wayland/pulseaudio too). Then the runtime/apps could be configured with modules to get ca:s from there.

Would this be a reasonable approach? And would it work for both OpenSSL and gnutls? Does it work already, or does it require any p11-kit work?

**Comment by nmav** [comment]
> Would this be a reasonable approach?

@alexlarsson [sorry for the late reply] it seems so

> And would it work for both OpenSSL and gnutls?

It depends how are they compiled. gnutls can be compiled to read the CA trust store from p11-kit trust module directly (fedora does that), and openssl may need to generate some file store from p11-kit.

> Does it work already, or does it require any p11-kit work?

It does. fedora uses p11-kit that way.

**Comment by alexlarsson** [comment]
> openssl may need to generate some file store from p11-kit.

What exactly do you mean by this? What and when would create these files? Suppose we're running in a sandbox with no files from the host, just a unix domain socket to p11y-kitd. Do we have to run some trigger on app startup to extract the current ca certs?

So, the other question is, what else but reading the ca-certs can you do via p11y-kitd? Can you add new root certs? I guess you can access smart cards? Thats maybe not ideal to export to all apps. Is there anything else that is problematic to give access to for "untrusted" code?

**Comment by stefwalter** [comment]
I tihnk we should make it so openssl doesn't need to build a filestore from p11-kit. Can we just do the work to make openssl access p11-kit directly for its certificates and trust?

**Comment by alexlarsson** [comment]
It seems to me that docker and other container system have similar requirements to this. I.e. you want to add a system-wide ca root on the host and have containers pick these up automatically. No?

**Comment by alexlarsson** [comment]
At least for the new work on "system containers".

**Comment by stefwalter** [comment]
A while back Openshift folks were also asking about this for their pods. To be able to mount trusted certificate files into containers, they way they bring the host resolv.conf in ... Again, depends on making this work seamlessly with OpenSSL ... due to a lot of containerized software using OpenSSL.

**Comment by nmav** [comment]
Given that the files are generated on the host, wouldn't bind mounting '/etc/pki' on containers and flatpak, "just" work? It contains files for openssl, gnutls, nss as well as java.

**Comment by stefwalter** [comment]
Right, if that is sorted out (separating trust related files from private keys) ... then we're in a good place for CA trust. The p11-kit ca-trust directories are already separate, others are intermingled.

**Comment by alexlarsson** [comment]
For the case of flatpak I'm specifically interested in p11-kitd because i *cannot* mount the pki files directly, since flatpak is cross-distribution and the file layout differs wildly between different distributions (and versions). The hope was to get a single, ABI-stable, long term supportable source for CA trust.

I understand that in a openshift on rhel running a rhel container we can just share /etc/pki, but that is just not good enough for me.

Of course, if anyone manages to sell a single standard for storing the ca roots for all distros then i can use that too.

**Comment by stefwalter** [comment]
PKCS#11 is that standard. But integration into OpenSSL is what needs to be finished, hence the reference to that above.

**Comment by alexlarsson** [comment]
Yes, pkcs#11 is good, but /etc/pki is not.

**Comment by nmav** [comment]
I wouldn't bet on openssl integration any time soon. Nevertheless, @alexlarsson what about what I suggested above. Use PKCS#11 for NSS and gnutls apps, and use the commands
```
/usr/bin/p11-kit extract --format=openssl-bundle --filter=certificates --overwrite --comment $DEST/openssl/ca-bundle.trust.crt
/usr/bin/p11-kit extract --format=pem-bundle --filter=ca-anchors --overwrite --comment --purpose server-auth $DEST/pem/tls-ca-bundle.pem
```
to generate the layout that openssl expects?

**Comment by alexlarsson** [comment]
I guess that would work. I could put it in a script so that only apps using openssl would need to call that on startup.

**Comment by kaie** [comment]
Is it possible that a flatpak application runs with root permissions? If yes, then a flatpak shouldn't access the host's p11-kit-trust.so module directly, because it can be used to change the host CA trust configuration.

**Comment by kaie** [comment]
p11y-kitd doesn't exist, right? You're suggesting a daemon that maps the PKCS#11 interface of p11-kit-trust.so to IPC?

**Comment by alexlarsson** [comment]
Its possible to run flatpaks as root, like you can any app. It is not how it normally is run it though.

**Comment by alexlarsson** [comment]
Its not named p11-kitd, but I believe there is something like this. I.e. a standard pkcs#11 module that talks to a service over a local socket which remotes the pkcs#11 api.
See: https://p11-glue.freedesktop.org/doc/p11-kit/p11-kit.html

**Comment by alexlarsson** [comment]
That said, the idea I had was for the server to expose a limited, essentially read-only view of the CAs, independent on the uid of the client. Not sure that is possible atm.

**Comment by kaie** [comment]
Applications based on OpenSSL may access the CA trust list in multiple formats. (a) directory with hashed files. (b) single file that provide a simple whitelist (PEM format with BEGIN CERTIFICATE entries). (c) single file that that supports whitelist (trusted) and blacklisted (distrusted) CAs.

I believe which one is used is configured at build time of openssl or the application.
What do you do if the application wants to use (a), but the host OS doesn't provide that?

Does Flatpak want to implement an abstraction layer for distribution specific configuration? If yes, see https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

If not, you probably have to continue with your current approach. I'm guessing you're currently including the ca-certificates package from a specific distribution, and require all applications in your Flatpaks to be configured according to the way that distributions provides the CA files. This means, that the host may not be able to provide the files in the format your applications expect.

Ideally there should be an initiative where distribution developers collaborate to create a cross-distribution standard for CA trust configuration, on which Flatpak could then depend at a later time.

**Comment by kaie** [comment]
If it were possible to support remote pkcs#11, it would be necessary to restrict Flatpak to only perform read-only operations.

**Comment by alexlarsson** [comment]
@kaie I'm aware that the current landscape is non-ideal, that is why i'm hoping that the remoted pkcs#11 solution could help us here. Basically that would create a single way to get the CA trust list in the sandbox, which could dynamically map to whatever format your distribution uses on the outside.

I'm aware that openssl cannot currently use pkcs#11 modules, but the other libs can, and this could conceivably be implemented, no?

And yes, the socket listening to the flatpak calls would have to be told to only allow read-only operations.

**Comment by alexlarsson** [comment]
Basically, I guess what I want is for flatpak to run something like: `p11-kit server pkcs11:p11-kit-trust-readonly` and then bind-mount the socket for that into the sandbox and set P11_KIT_SERVER_ADDRESS to point to that.

Or maybe it would be `p11-kit server --readonly pkcs11:p11-kit-trust`? I honestly don't know very much about pkcs#11.

**Comment by alexlarsson** [comment]
And then its up to the application to bundle p11-kit-client.so and configure the ssl libs and apps to use that.

**Comment by alexlarsson** [comment]
(And it would be up to the distribution to make p11-kit-trust work with the CA trust list format the distro uses.)

**Comment by nmav** [comment]
@alexlarsson is that addressed by #129 ?

**Comment by alexlarsson** [comment]
@nmav It looks pretty good to me. Some questions:

If i want to use this, i so:
```
p11-kit server --provider p11-kit-trust.so "pkcs11:model=p11-kit-trust?write-protected=yes"
```
on the host side, and then bind mount the resulting socket as `/run/user/1000/p11-kit/pkcs11` in the host.

Then if you do `p11tool --list-tokens --provider=p11-kit-client.so` this will list the host things. But how would you change the configuration so that this is the default setup? Ideally it should look at this by default but if the socket is not there fall back to the default trust paths.

**Comment by nmav** [comment]
If you configure p11-kit.conf in the sandbox to register p11-kit-client wouldn't it work?

**Comment by alexlarsson** [comment]
Is there some way to probe the version of p11-kit at runtime? `p11-kit --version` doesn't seem to exist.

**Comment by alexlarsson** [comment]
Alternatively how can i otherwise check if write-protected is supported?

**Comment by alexlarsson** [comment]
Hmm. I'm still not sure how to do this.
I just pushed this WIP branch: https://github.com/alexlarsson/flatpak/tree/p11kit-proxy
With this, I automatically get a server running in the desktop session, and its socket is mounted as `/run/user/1000/p11-kit/pkcs11` in the sandbox.

In the sandbox, if I run `p11tool --list-all-certs` i get the default ca-certs that are shipped with the flatpak runtime.

If instead i run `p11tool --list-all-certs  --provider=p11-kit-client.so pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust` (I need to specify a token here), then I get the host certificates.

This is *almost* what I want. The only thing that is missing, is that I want p11-kit in the sandbox to automatically chose the p11-kit-client.so provider, if, and only if, the sandbox has the p11kit server socket mounted in it.

I understand from the above comment that I need to somehow generate a `p11-kit.conf` file. But what should be in it, and where should i put it?

**Comment by ueno** [comment]
I think you can put:
```
module: p11-kit-client.so
```
in
`~/.config/pkcs11/modules/p11-kit-client.module`.

**Comment by alexlarsson** [comment]
Ok, i updated this and its now a PR at: https://github.com/flatpak/flatpak/pull/1757

What i did was create a `/etc/pkcs11/modules/p11-kit-trust.module` file that just contains:
```
# This overrides the runtime p11-kit-trusted module with a client one talking to the trust module on the host
module: p11-kit-client.so
```

This file is only created if we actually spawned the server, and it overrides the module loaded for the trust module in the sandbox, so that it instead talks to the host trusted module.

Does this make sense to you?

**Comment by stefwalter** [comment]
Makes sense for me. This is how overrides are supposed to work
